lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # ruta al private.pem
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # ruta al public.pem
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # segundos, ejemplo 1 hora

